import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { dateTime } from "@/lib/format";
import { CalendarDays, MapPin, Plus } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function CalendarPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const events = trpc.sports.events.useQuery({ limit: 200 }); const seasons = trpc.sports.seasons.useQuery();
  const createEvent = trpc.sports.createEvent.useMutation({ onSuccess: () => { utils.sports.events.invalidate(); toast.success("Evento añadido al calendario."); } });
  const [showForm, setShowForm] = useState(false); const [type, setType] = useState<"training" | "general">("training"); const [title, setTitle] = useState(""); const [start, setStart] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [seasonId, setSeasonId] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!start) return toast.error("Indica fecha y hora."); await createEvent.mutateAsync({ type, title, startsAt: new Date(start), location: location || null, description: description || null, seasonId: seasonId ? Number(seasonId) : null }); setShowForm(false); setTitle(""); setStart(""); setLocation(""); setDescription(""); };
  return <div><PageHeader eyebrow="Agenda compartida" title="El equipo sabe dónde estar." description="Entrenamientos, partidos y eventos del club en un calendario visible para todos los miembros." action={isAdmin ? <Button onClick={() => setShowForm(!showForm)} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Añadir evento</Button> : undefined} />
    {showForm && isAdmin ? <form onSubmit={submit} className="paper-card mb-7 p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-2"><Label>Tipo</Label><Select value={type} onValueChange={value => setType(value as "training" | "general")}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="training">Entrenamiento</SelectItem><SelectItem value="general">Evento</SelectItem></SelectContent></Select></div><CalendarField label="Título" value={title} onChange={setTitle} required /><CalendarField label="Fecha y hora" value={start} onChange={setStart} type="datetime-local" required /><div className="space-y-2"><Label>Temporada</Label><Select value={seasonId || "none"} onValueChange={value => setSeasonId(value === "none" ? "" : value)}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Sin asignar" /></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{seasons.data?.map(season => <SelectItem key={season.id} value={String(season.id)}>{season.name}</SelectItem>)}</SelectContent></Select></div><CalendarField label="Lugar" value={location} onChange={setLocation} /><div className="space-y-2 md:col-span-2 xl:col-span-4"><Label>Descripción</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} className="rounded-xl" /></div></div><div className="mt-5 flex justify-end"><Button type="submit" className="rounded-xl">Guardar evento</Button></div></form> : null}
    <section className="space-y-3">{events.data?.length ? events.data.map(item => <article key={item.event.id} className="paper-card flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex h-16 w-16 shrink-0 flex-col items-center justify-center rounded-2xl bg-secondary text-secondary-foreground"><span className="text-lg font-bold">{new Date(item.event.startsAt).getDate()}</span><span className="text-[0.65rem] font-bold uppercase">{new Intl.DateTimeFormat("es-ES", { month: "short" }).format(new Date(item.event.startsAt))}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold">{item.event.title}</h2><Badge className={item.event.type === "match" ? "bg-amber-100 text-amber-800 hover:bg-amber-100" : item.event.type === "training" ? "bg-sky-100 text-sky-800 hover:bg-sky-100" : "bg-stone-100 text-stone-800 hover:bg-stone-100"}>{item.event.type === "match" ? "Partido" : item.event.type === "training" ? "Entrenamiento" : "Evento"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{dateTime(item.event.startsAt)}{item.event.location ? ` · ${item.event.location}` : ""}</p>{item.event.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{item.event.description}</p> : null}</div>{item.event.location ? <span className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{item.event.location}</span> : null}</article>) : <article className="paper-card p-9 text-center"><CalendarDays className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">No hay eventos programados todavía.</p></article>}</section>
  </div>;
}
function CalendarField({ label, value, onChange, type = "text", required }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <div className="space-y-2"><Label>{label}</Label><Input className="rounded-xl" value={value} onChange={event => onChange(event.target.value)} type={type} required={required} /></div>; }
