import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { dateTime } from "@/lib/format";
import { CalendarDays, Check, Clock3, MapPin, Plus, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function CalendarPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const events = trpc.sports.events.useQuery({ limit: 200 }); const seasons = trpc.sports.seasons.useQuery();
  const createEvent = trpc.sports.createEvent.useMutation({ onSuccess: () => { utils.sports.events.invalidate(); utils.sports.nextSummary.invalidate(); toast.success("Actividad añadida al calendario."); } });
  const respond = trpc.sports.respondAttendance.useMutation({ onSuccess: () => { utils.sports.events.invalidate(); utils.sports.nextSummary.invalidate(); toast.success("Asistencia actualizada."); } });
  const [showForm, setShowForm] = useState(false); const [type, setType] = useState<"training" | "general">("training"); const [title, setTitle] = useState("Entrenamiento"); const [start, setStart] = useState(""); const [callAt, setCallAt] = useState(""); const [location, setLocation] = useState(""); const [description, setDescription] = useState(""); const [seasonId, setSeasonId] = useState(""); const [attendanceEnabled, setAttendanceEnabled] = useState(true);
  const setActivityType = (value: "training" | "general") => { setType(value); setAttendanceEnabled(value === "training"); if (value === "training" && title === "") setTitle("Entrenamiento"); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!start) return toast.error("Indica fecha y hora."); await createEvent.mutateAsync({ type, title: title || (type === "training" ? "Entrenamiento" : "Evento"), startsAt: new Date(start), callAt: callAt ? new Date(callAt) : null, location: location || null, description: description || null, attendanceEnabled, seasonId: seasonId ? Number(seasonId) : null }); setShowForm(false); setTitle(""); setStart(""); setCallAt(""); setLocation(""); setDescription(""); };
  return <div><PageHeader eyebrow="Agenda compartida" title="Entrenar también es confirmar." description="Programa entrenamientos, consulta la convocatoria y deja tu respuesta de asistencia sin salir del calendario." action={isAdmin ? <Button onClick={() => setShowForm(!showForm)} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Programar actividad</Button> : undefined} />
    {showForm && isAdmin ? <form onSubmit={submit} className="paper-card mb-7 p-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-2"><Label>Tipo</Label><Select value={type} onValueChange={value => setActivityType(value as "training" | "general")}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="training">Entrenamiento</SelectItem><SelectItem value="general">Evento</SelectItem></SelectContent></Select></div><CalendarField label="Título" value={title} onChange={setTitle} placeholder={type === "training" ? "Entrenamiento" : "Evento"} /><CalendarField label="Fecha y hora" value={start} onChange={setStart} type="datetime-local" required /><CalendarField label="Hora de estar" value={callAt} onChange={setCallAt} type="datetime-local" /><div className="space-y-2"><Label>Temporada</Label><Select value={seasonId || "none"} onValueChange={value => setSeasonId(value === "none" ? "" : value)}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Sin asignar" /></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{seasons.data?.map(season => <SelectItem key={season.id} value={String(season.id)}>{season.name}</SelectItem>)}</SelectContent></Select></div><CalendarField label="Lugar" value={location} onChange={setLocation} /><label className="flex items-center gap-3 rounded-xl border border-border bg-secondary/35 px-4 py-3 text-sm font-semibold"><input type="checkbox" checked={attendanceEnabled} onChange={event => setAttendanceEnabled(event.target.checked)} className="h-4 w-4 accent-primary" />Solicitar asistencia</label><div className="space-y-2 md:col-span-2 xl:col-span-4"><Label>Descripción</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} className="rounded-xl" placeholder="Indicaciones del entrenamiento, material, pista…" /></div></div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Cancelar</Button><Button type="submit" disabled={createEvent.isPending} className="rounded-xl">Guardar actividad</Button></div></form> : null}
    <section className="space-y-3">{events.data?.length ? events.data.map(item => <article key={item.event.id} className="paper-card flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex h-16 w-16 shrink-0 flex-col items-center justify-center rounded-2xl bg-secondary text-secondary-foreground"><span className="text-lg font-bold">{new Date(item.event.startsAt).getDate()}</span><span className="text-[0.65rem] font-bold uppercase">{new Intl.DateTimeFormat("es-ES", { month: "short" }).format(new Date(item.event.startsAt))}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold">{item.event.title}</h2><Badge className={item.event.type === "match" ? "bg-amber-100 text-amber-800 hover:bg-amber-100" : item.event.type === "training" ? "bg-sky-100 text-sky-800 hover:bg-sky-100" : "bg-stone-100 text-stone-800 hover:bg-stone-100"}>{item.event.type === "match" ? "Partido" : item.event.type === "training" ? "Entrenamiento" : "Evento"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{dateTime(item.event.startsAt)}{item.event.location ? ` · ${item.event.location}` : ""}</p>{item.event.callAt ? <p className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-sky-800"><Clock3 className="h-4 w-4" />Hora de estar: {dateTime(item.event.callAt)}</p> : null}{item.event.description ? <p className="mt-2 text-sm leading-6 text-muted-foreground">{item.event.description}</p> : null}{item.event.attendanceEnabled ? <div className="mt-3 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs font-semibold text-muted-foreground">Asistencia · {item.attendance.going} sí / {item.attendance.maybe} quizá / {item.attendance.notGoing} no</span><AttendanceButton active={item.attendance.mine === "going"} icon={<Check className="h-3.5 w-3.5" />} label="Voy" onClick={() => respond.mutate({ eventId: item.event.id, status: "going" })} /><AttendanceButton active={item.attendance.mine === "maybe"} icon={<Clock3 className="h-3.5 w-3.5" />} label="Quizá" onClick={() => respond.mutate({ eventId: item.event.id, status: "maybe" })} /><AttendanceButton active={item.attendance.mine === "not_going"} icon={<X className="h-3.5 w-3.5" />} label="No voy" onClick={() => respond.mutate({ eventId: item.event.id, status: "not_going" })} /></div> : null}</div>{item.event.location ? <span className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground"><MapPin className="h-3.5 w-3.5" />{item.event.location}</span> : null}</article>) : <article className="paper-card p-9 text-center"><CalendarDays className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">No hay actividades programadas todavía.</p></article>}</section>
  </div>;
}
function AttendanceButton({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <Button type="button" size="sm" variant={active ? "default" : "outline"} onClick={onClick} className="rounded-lg">{icon}<span className="ml-1.5">{label}</span></Button>; }
function CalendarField({ label, value, onChange, type = "text", required, placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; placeholder?: string }) { return <div className="space-y-2"><Label>{label}</Label><Input className="rounded-xl" value={value} onChange={event => onChange(event.target.value)} type={type} required={required} placeholder={placeholder} /></div>; }
