import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { euro, shortDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ArrowLeftRight, Check, CircleDollarSign, Clock3, Landmark, Plus, ReceiptText, Repeat2, WalletCards } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const toCents = (value: string) => Math.round(Number(value.replace(",", ".")) * 100);
const today = () => new Date().toISOString().slice(0, 10);
type PaymentMethod = "cash" | "bank_transfer" | "bizum" | "paypal";
type PlayerStatement = { charges: Array<{ id: number; concept: string; status: "open" | "cancelled" | "settled"; amountCents: number }>; payments: Array<{ id: number; concept: string | null; method: PaymentMethod; status: "pending" | "confirmed" | "rejected"; amountCents: number }> };

export default function FinancesPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const statement = trpc.finance.myStatement.useQuery(undefined, { enabled: !isAdmin });
  const ledger = trpc.finance.ledger.useQuery(undefined, { enabled: isAdmin });
  const queue = trpc.finance.paymentQueue.useQuery(undefined, { enabled: isAdmin });
  const balances = trpc.finance.playerBalances.useQuery(undefined, { enabled: isAdmin });
  const seasons = trpc.sports.seasons.useQuery(undefined, { enabled: isAdmin });
  const submit = trpc.finance.submitPayment.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Pago enviado. Queda pendiente de confirmar."); } });
  const review = trpc.finance.reviewPayment.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Pago revisado."); } });
  const quick = trpc.finance.quickTransaction.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Movimiento registrado desde el concepto predefinido."); } });
  const recordPayment = trpc.finance.recordAdminPayment.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Cobro confirmado y registrado."); } });
  const createAccount = trpc.finance.createAccount.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Caja creada."); } });
  const createTemplate = trpc.finance.createTemplate.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Concepto predefinido creado."); } });
  const createPlan = trpc.finance.createFeePlan.useMutation({ onSuccess: data => { utils.finance.invalidate(); toast.success(data.createdCharges ? `Cuota creada; ${data.createdCharges} cargos ya vencidos generados.` : "Cuota programada creada."); } });
  const transfer = trpc.finance.transferBetweenAccounts.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Transferencia entre cajas registrada."); } });
  const [payAmount, setPayAmount] = useState(""); const [method, setMethod] = useState<PaymentMethod>("bizum"); const [note, setNote] = useState(""); const [chargeId, setChargeId] = useState("none");
  const [mode, setMode] = useState<"movement" | "payment" | "plan" | "account" | "template" | "transfer" | "close" | null>(null);
  const [defaultAccount, setDefaultAccount] = useState("none");
  const [templateId, setTemplateId] = useState("none"); const [movementAccount, setMovementAccount] = useState("none"); const [movementAmount, setMovementAmount] = useState(""); const [movementDate, setMovementDate] = useState(today());
  const [adminPlayer, setAdminPlayer] = useState("none"); const [adminCharge, setAdminCharge] = useState("none"); const [adminAmount, setAdminAmount] = useState(""); const [adminMethod, setAdminMethod] = useState<PaymentMethod>("bizum"); const [adminConcept, setAdminConcept] = useState("none"); const [adminPaymentDate, setAdminPaymentDate] = useState(today());
  const [accountName, setAccountName] = useState(""); const [holderName, setHolderName] = useState(""); const [accountType, setAccountType] = useState<"cash" | "bank" | "digital">("cash"); const [openingBalance, setOpeningBalance] = useState("0");
  const [templateName, setTemplateName] = useState(""); const [templateConcept, setTemplateConcept] = useState(""); const [templateDirection, setTemplateDirection] = useState<"income" | "expense">("expense"); const [templateAmount, setTemplateAmount] = useState(""); const [templateAccount, setTemplateAccount] = useState("none");
  const [planSeason, setPlanSeason] = useState("none"); const [planName, setPlanName] = useState("Cuota de liga"); const [planConcept, setPlanConcept] = useState("Liga"); const [firstDate, setFirstDate] = useState("2026-09-01"); const [secondDate, setSecondDate] = useState("2027-02-01"); const [feeAmount, setFeeAmount] = useState("60");
  const [sourceAccount, setSourceAccount] = useState("none"); const [targetAccount, setTargetAccount] = useState("none"); const [transferAmount, setTransferAmount] = useState(""); const [transferDate, setTransferDate] = useState(today());
  const [historyAccount, setHistoryAccount] = useState("none"); const [historySeason, setHistorySeason] = useState("none"); const [historyDirection, setHistoryDirection] = useState<"all" | "income" | "expense">("all");
  const [nextSeasonName, setNextSeasonName] = useState(""); const [nextSeasonStart, setNextSeasonStart] = useState(""); const [nextSeasonEnd, setNextSeasonEnd] = useState("");
  const accounts = ledger.data?.accounts ?? []; const templates = ledger.data?.templates ?? []; const players = balances.data ?? [];
  const chooseHabitual = (id: string) => { setTemplateId(id); const template = templates.find(item => String(item.id) === id); if (!template) return; setMovementAmount(template.defaultAmountCents ? String(template.defaultAmountCents / 100) : ""); setMovementAccount(template.defaultAccountId ? String(template.defaultAccountId) : "none"); setMode("movement"); };
  const historyInput = useMemo(() => ({ accountId: historyAccount === "none" ? null : Number(historyAccount), seasonId: historySeason === "none" ? null : Number(historySeason), direction: historyDirection }), [historyAccount, historyDirection, historySeason]);
  const history = trpc.finance.accountHistory.useQuery(historyInput, { enabled: isAdmin });
  const closePreview = trpc.finance.seasonClosePreview.useQuery(undefined, { enabled: isAdmin && mode === "close" });
  const closeSeason = trpc.finance.closeSeason.useMutation({ onSuccess: () => { utils.invalidate(); toast.success("Nueva temporada abierta. Las cajas conservan su saldo."); reset(); } });
  const reset = () => setMode(null);
  const submitPlayerPayment = async (event: FormEvent): Promise<void> => { event.preventDefault(); const amountCents = toCents(payAmount); if (!amountCents) { toast.error("Indica un importe válido."); return; } await submit.mutateAsync({ amountCents, method, paidAt: new Date(), chargeId: chargeId === "none" ? null : Number(chargeId), playerNote: note || null }); setPayAmount(""); setNote(""); };
  const saveQuickMovement = async (event: FormEvent) => { event.preventDefault(); if (templateId === "none") return toast.error("Selecciona un concepto predefinido."); const amountCents = movementAmount ? toCents(movementAmount) : null; if (movementAmount && !amountCents) return toast.error("Indica un importe válido."); await quick.mutateAsync({ templateId: Number(templateId), accountId: movementAccount === "none" ? null : Number(movementAccount), amountCents, occurredAt: new Date(`${movementDate}T12:00:00`) }); setMovementAmount(""); reset(); };
  const saveAdminPayment = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(adminAmount); if (adminPlayer === "none" || !amountCents || adminConcept === "none") return toast.error("Selecciona jugador, concepto e importe."); await recordPayment.mutateAsync({ playerId: Number(adminPlayer), chargeId: adminCharge === "none" ? null : Number(adminCharge), accountId: defaultAccount === "none" ? null : Number(defaultAccount), amountCents, paidAt: new Date(`${adminPaymentDate}T12:00:00`), method: adminMethod, concept: adminConcept }); setAdminAmount(""); setAdminConcept("none"); reset(); };
  const saveAccount = async (event: FormEvent) => { event.preventDefault(); if (!accountName) return; await createAccount.mutateAsync({ name: accountName, holderName: holderName || null, type: accountType, openingBalanceCents: toCents(openingBalance) || 0 }); setAccountName(""); setHolderName(""); reset(); };
  const saveTemplate = async (event: FormEvent) => { event.preventDefault(); const amount = templateAmount ? toCents(templateAmount) : null; if (!templateName || !templateConcept) return toast.error("Indica el nombre y el concepto."); await createTemplate.mutateAsync({ name: templateName, direction: templateDirection, defaultConcept: templateConcept, defaultAmountCents: amount, defaultAccountId: templateAccount === "none" ? null : Number(templateAccount) }); setTemplateName(""); setTemplateConcept(""); setTemplateAmount(""); reset(); };
  const savePlan = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(feeAmount); if (planSeason === "none" || !amountCents || !firstDate || !secondDate) return toast.error("Completa temporada, importe y ambas fechas."); await createPlan.mutateAsync({ seasonId: Number(planSeason), name: planName, concept: planConcept, installments: [{ label: "Primer pago", amountCents, dueAt: new Date(`${firstDate}T12:00:00`) }, { label: "Segundo pago", amountCents, dueAt: new Date(`${secondDate}T12:00:00`) }] }); reset(); };
  const saveTransfer = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(transferAmount); if (sourceAccount === "none" || targetAccount === "none" || !amountCents) return toast.error("Completa origen, destino e importe."); await transfer.mutateAsync({ sourceAccountId: Number(sourceAccount), destinationAccountId: Number(targetAccount), amountCents, occurredAt: new Date(`${transferDate}T12:00:00`) }); setTransferAmount(""); reset(); };
  const saveSeasonClose = async (event: FormEvent) => { event.preventDefault(); if (!nextSeasonName || !nextSeasonStart || !nextSeasonEnd) return toast.error("Completa nombre y fechas de la nueva temporada."); await closeSeason.mutateAsync({ name: nextSeasonName, startsAt: new Date(`${nextSeasonStart}T12:00:00`), endsAt: new Date(`${nextSeasonEnd}T12:00:00`) }); };

  if (!isAdmin) return <PlayerView statement={statement.data} payAmount={payAmount} setPayAmount={setPayAmount} method={method} setMethod={setMethod} note={note} setNote={setNote} chargeId={chargeId} setChargeId={setChargeId} submit={submitPlayerPayment} pending={submit.isPending} />;

  const owed = players.reduce((sum, item) => sum + Math.max(item.summary.balanceCents, 0), 0);
  const activeSeason = seasons.data?.find(season => season.isCurrent);
  return <div><PageHeader eyebrow="Contabilidad" title="La caja, bajo control." description="Registra un cobro o gasto en pocos clics, programa cuotas y conoce el saldo de cada responsable." action={<div className="flex flex-wrap items-center gap-2"><Badge variant="secondary" className="rounded-xl px-3 py-2">Temporada activa · {activeSeason?.name ?? "Sin definir"}</Badge><Button onClick={() => setMode("plan")} variant="outline" className="rounded-xl"><Repeat2 className="mr-2 h-4 w-4" />Cuota programada</Button><Button onClick={() => setMode("movement")} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Movimiento rápido</Button></div>} />
    <section className="grid gap-4 md:grid-cols-3"><BalanceTile label="Saldo consolidado" value={euro(ledger.data?.generalBalanceCents ?? 0)} icon={<CircleDollarSign className="h-5 w-5" />} /><BalanceTile label="Por cobrar" value={euro(owed)} icon={<ReceiptText className="h-5 w-5" />} /><BalanceTile label="Pagos pendientes" value={String(queue.data?.length ?? 0)} icon={<Clock3 className="h-5 w-5" />} /></section>
    <section className="mt-6 flex flex-wrap gap-2"><ActionChip icon={<WalletCards className="h-4 w-4" />} label="Nueva caja" onClick={() => setMode("account")} /><ActionChip icon={<ReceiptText className="h-4 w-4" />} label="Nuevo concepto" onClick={() => setMode("template")} /><ActionChip icon={<Check className="h-4 w-4" />} label="Registrar cobro" onClick={() => setMode("payment")} /><ActionChip icon={<ArrowLeftRight className="h-4 w-4" />} label="Transferir entre cajas" onClick={() => setMode("transfer")} /><ActionChip icon={<Landmark className="h-4 w-4" />} label="Cerrar temporada" onClick={() => setMode("close")} /></section>
    <section className="paper-card mt-5 p-5"><p className="eyebrow">Movimientos habituales</p><div className="mt-3 flex flex-wrap gap-2">{templates.length ? templates.map(item => <Button key={item.id} onClick={() => chooseHabitual(String(item.id))} variant="outline" className="rounded-xl">{item.name}{item.defaultAmountCents ? <span className="ml-2 text-muted-foreground">{euro(item.defaultAmountCents)}</span> : null}</Button>) : <p className="text-sm text-muted-foreground">Crea un concepto habitual para registrar ingresos y gastos sin volver a escribir sus datos.</p>}</div></section>
    {mode === "movement" ? <form onSubmit={saveQuickMovement} className="paper-card mt-6 grid gap-4 p-5 md:grid-cols-5"><SelectField label="Concepto habitual" value={templateId} onChange={chooseHabitual} options={templates.map(item => ({ value: String(item.id), label: `${item.name}${item.defaultAmountCents ? ` · ${euro(item.defaultAmountCents)}` : ""}` }))} /><div className="rounded-xl border border-border bg-secondary/35 px-4 py-3 text-sm"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Datos precargados</p><p className="mt-1 font-semibold">{templates.find(item => String(item.id) === templateId)?.defaultConcept || "Selecciona un movimiento"}</p><p className="mt-1 text-xs text-muted-foreground">{templates.find(item => String(item.id) === templateId)?.direction === "income" ? "Ingreso" : templates.find(item => String(item.id) === templateId)?.direction === "expense" ? "Gasto" : "Tipo pendiente"}</p></div><SelectField label="Caja o cuenta" value={movementAccount} onChange={setMovementAccount} options={accounts.filter(item => item.account.isActive).map(item => ({ value: String(item.account.id), label: item.account.name }))} /><FormField label="Importe (€)" value={movementAmount} onChange={setMovementAmount} type="number" step="0.01" placeholder="Usar valor del concepto" /><DateField label="Fecha" value={movementDate} onChange={setMovementDate} /><div className="md:col-span-5 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" disabled={quick.isPending} className="rounded-xl">Registrar</Button></div></form> : null}
    {mode === "payment" ? <form onSubmit={saveAdminPayment} className="paper-card mt-6 grid gap-4 p-5 lg:grid-cols-7"><SelectField label="Jugador" value={adminPlayer} onChange={setAdminPlayer} options={players.filter(item => item.player.status === "active" && item.player.isActiveCurrentSeason).map(item => ({ value: String(item.player.id), label: item.player.fullName }))} /><SelectField label="Concepto" value={adminConcept} onChange={setAdminConcept} options={templates.filter(item => item.direction === "income").map(item => ({ value: item.defaultConcept, label: item.name }))} /><SelectField label="Cargo" value={adminCharge} onChange={setAdminCharge} options={(ledger.data?.charges ?? []).filter(item => item.charge.playerId === Number(adminPlayer) && item.charge.status === "open").map(item => ({ value: String(item.charge.id), label: `${item.charge.concept} · ${euro(item.charge.amountCents)}` }))} /><SelectField label="Caja receptora" value={defaultAccount} onChange={setDefaultAccount} options={accounts.filter(item => item.account.isActive).map(item => ({ value: String(item.account.id), label: item.account.name }))} /><FormField label="Importe (€)" value={adminAmount} onChange={setAdminAmount} type="number" step="0.01" required /><DateField label="Fecha" value={adminPaymentDate} onChange={setAdminPaymentDate} /><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" disabled={recordPayment.isPending} className="flex-1 rounded-xl">Confirmar cobro</Button></div><SelectField label="Método" value={adminMethod} onChange={value => setAdminMethod(value as PaymentMethod)} options={[{ value: "cash", label: "Efectivo" }, { value: "bank_transfer", label: "Transferencia" }, { value: "bizum", label: "Bizum" }, { value: "paypal", label: "PayPal" }]} noNone /></form> : null}
    {mode === "plan" ? <form onSubmit={savePlan} className="paper-card mt-6 grid gap-4 p-5 lg:grid-cols-6"><SelectField label="Temporada" value={planSeason} onChange={setPlanSeason} options={seasons.data?.map(item => ({ value: String(item.id), label: item.name })) ?? []} /><FormField label="Nombre de cuota" value={planName} onChange={setPlanName} required /><FormField label="Concepto" value={planConcept} onChange={setPlanConcept} required /><FormField label="Importe de cada pago (€)" value={feeAmount} onChange={setFeeAmount} type="number" step="0.01" required /><DateField label="Primer vencimiento" value={firstDate} onChange={setFirstDate} /><DateField label="Segundo vencimiento" value={secondDate} onChange={setSecondDate} /><div className="lg:col-span-6 flex items-center justify-between gap-3 rounded-xl bg-secondary/60 px-4 py-3 text-sm text-muted-foreground"><span>Se generará un cargo para cada jugador activo cuando llegue cada vencimiento.</span><div className="flex gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" disabled={createPlan.isPending} className="rounded-xl">Programar 2 cuotas</Button></div></div></form> : null}
    {mode === "account" ? <form onSubmit={saveAccount} className="paper-card mt-6 grid gap-4 p-5 md:grid-cols-5"><FormField label="Nombre de caja" value={accountName} onChange={setAccountName} placeholder="Caja Juanlu" required /><FormField label="Titular responsable" value={holderName} onChange={setHolderName} placeholder="Juanlu" /><SelectField label="Tipo" value={accountType} onChange={value => setAccountType(value as "cash" | "bank" | "digital")} options={[{ value: "cash", label: "Efectivo" }, { value: "bank", label: "Banco" }, { value: "digital", label: "Digital" }]} noNone /><FormField label="Saldo inicial (€)" value={openingBalance} onChange={setOpeningBalance} type="number" step="0.01" /><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" className="flex-1 rounded-xl">Crear caja</Button></div></form> : null}
    {mode === "template" ? <form onSubmit={saveTemplate} className="paper-card mt-6 grid gap-4 p-5 md:grid-cols-5"><FormField label="Nombre de acceso rápido" value={templateName} onChange={setTemplateName} placeholder="Pago de pista" required /><FormField label="Concepto contable" value={templateConcept} onChange={setTemplateConcept} placeholder="Alquiler de pista" required /><SelectField label="Tipo" value={templateDirection} onChange={value => setTemplateDirection(value as "income" | "expense")} options={[{ value: "expense", label: "Gasto" }, { value: "income", label: "Ingreso" }]} noNone /><FormField label="Importe habitual (€)" value={templateAmount} onChange={setTemplateAmount} type="number" step="0.01" /><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" className="flex-1 rounded-xl">Guardar concepto</Button></div></form> : null}
    {mode === "transfer" ? <form onSubmit={saveTransfer} className="paper-card mt-6 grid gap-4 p-5 md:grid-cols-5"><SelectField label="Caja de origen" value={sourceAccount} onChange={setSourceAccount} options={accounts.map(item => ({ value: String(item.account.id), label: item.account.name }))} /><SelectField label="Caja de destino" value={targetAccount} onChange={setTargetAccount} options={accounts.map(item => ({ value: String(item.account.id), label: item.account.name }))} /><FormField label="Importe (€)" value={transferAmount} onChange={setTransferAmount} type="number" step="0.01" required /><DateField label="Fecha" value={transferDate} onChange={setTransferDate} /><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" className="flex-1 rounded-xl">Transferir</Button></div></form> : null}
    <section className="mt-7 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Cajas y responsables</p><h2 className="display-face mt-1 text-2xl">Dónde está el dinero</h2></div><div className="divide-y divide-border/70">{accounts.length ? accounts.map(item => <div key={item.account.id} className="flex items-center justify-between px-6 py-4"><div><p className="font-semibold">{item.account.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.account.holderName || "Sin responsable"} · {item.account.type === "cash" ? "Efectivo" : item.account.type === "bank" ? "Banco" : "Digital"}</p></div><p className="text-lg font-bold">{euro(item.balanceCents)}</p></div>) : <Empty text="Crea la caja de Juanlu y la de Maline para empezar a repartir los saldos." />}</div></article><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Cuotas programadas</p><h2 className="display-face mt-1 text-2xl">Próximos vencimientos</h2></div><div className="divide-y divide-border/70">{ledger.data?.feeInstallments.length ? ledger.data.feeInstallments.slice(0, 8).map(item => <div key={item.id} className="flex items-center justify-between px-6 py-4"><div><p className="font-semibold">{item.label}</p><p className="mt-1 text-xs text-muted-foreground">Vence {shortDate(item.dueAt)}</p></div><p className="font-bold">{euro(item.amountCents)}</p></div>) : <Empty text="Programa las cuotas de liga para que aparezcan automáticamente al llegar la fecha." />}</div></article></section>
    <section className="mt-7 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Confirmaciones</p><h2 className="display-face mt-1 text-2xl">Pagos pendientes</h2></div><div className="divide-y divide-border/70">{queue.data?.length ? queue.data.map(item => <div key={item.payment.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p className="font-semibold">{item.playerName}</p><p className="mt-1 text-xs text-muted-foreground">{item.chargeConcept || item.payment.concept || "Pago sin concepto"} · {shortDate(item.payment.paidAt)}</p></div><div className="flex gap-2"><p className="mr-2 self-center font-bold">{euro(item.payment.amountCents)}</p><Button onClick={() => review.mutate({ id: item.payment.id, decision: "confirmed", accountId: defaultAccount === "none" ? null : Number(defaultAccount) })} size="sm" className="rounded-lg">Confirmar</Button><Button onClick={() => review.mutate({ id: item.payment.id, decision: "rejected" })} size="sm" variant="ghost" className="rounded-lg">Rechazar</Button></div></div>) : <Empty text="No hay pagos esperando revisión." />}</div></article><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Saldos individuales</p><h2 className="display-face mt-1 text-2xl">Quién debe</h2></div><div className="divide-y divide-border/70">{players.filter(item => item.summary.balanceCents !== 0).slice(0, 8).map(item => <div className="flex items-center justify-between px-6 py-4" key={item.player.id}><p className="text-sm font-semibold">{item.player.fullName}</p><p className={item.summary.balanceCents > 0 ? "font-bold text-rose-700" : "font-bold text-emerald-700"}>{euro(item.summary.balanceCents)}</p></div>) || <Empty text="Sin saldos pendientes." />}</div></article></section>
    {mode === "close" ? <form onSubmit={saveSeasonClose} className="paper-card mt-7 grid gap-4 p-6 lg:grid-cols-4"><div className="lg:col-span-4"><p className="eyebrow">Cierre de temporada</p><h2 className="display-face mt-1 text-2xl">Abrir una temporada limpia</h2><p className="mt-2 text-sm text-muted-foreground">Las cajas conservan su saldo. Los cargos y pagos de jugadores permanecen archivados en la temporada que se cierra.</p></div><FormField label="Nueva temporada" value={nextSeasonName} onChange={setNextSeasonName} placeholder="Temporada 2027–2028" required /><DateField label="Inicio" value={nextSeasonStart} onChange={setNextSeasonStart} /><DateField label="Fin" value={nextSeasonEnd} onChange={setNextSeasonEnd} /><div className="rounded-xl bg-secondary/60 px-4 py-3 text-sm"><p className="font-semibold">Vista previa</p><p className="mt-1 text-muted-foreground">{closePreview.data?.openCharges ?? 0} cargos abiertos y {closePreview.data?.accountBalances.length ?? 0} cajas se conservarán.</p></div><div className="lg:col-span-4 flex justify-end gap-2"><Button type="button" variant="ghost" onClick={reset}>Cancelar</Button><Button type="submit" disabled={closeSeason.isPending} className="rounded-xl">Abrir nueva temporada</Button></div></form> : null}
    <section className="mt-7 paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Histórico de cajas</p><h2 className="display-face mt-1 text-2xl">Entradas, salidas y transferencias</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><SelectField label="Caja" value={historyAccount} onChange={setHistoryAccount} options={accounts.map(item => ({ value: String(item.account.id), label: item.account.name }))} noneLabel="Todas las cajas" /><SelectField label="Temporada" value={historySeason} onChange={setHistorySeason} options={seasons.data?.map(item => ({ value: String(item.id), label: item.name })) ?? []} noneLabel="Todas las temporadas" /><SelectField label="Tipo" value={historyDirection} onChange={value => setHistoryDirection(value as "all" | "income" | "expense")} options={[{ value: "all", label: "Todos" }, { value: "income", label: "Entradas" }, { value: "expense", label: "Salidas" }]} noNone /></div></div><div className="divide-y divide-border/70">{history.data?.length ? history.data.slice(0, 15).map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p className="font-semibold">{item.concept}</p><p className="mt-1 text-xs text-muted-foreground">{shortDate(item.occurredAt)}{item.playerName ? ` · ${item.playerName}` : ""}{item.transferKey ? " · Transferencia" : ""}</p></div><p className={item.direction === "income" ? "font-bold text-emerald-700" : "font-bold text-rose-700"}>{item.direction === "income" ? "+" : "−"}{euro(item.amountCents)}</p></div>) : <Empty text="No hay movimientos con los filtros seleccionados." />}</div></section>
  </div>;
}

function PlayerView({ statement, payAmount, setPayAmount, method, setMethod, note, setNote, chargeId, setChargeId, submit, pending }: { statement: PlayerStatement | undefined; payAmount: string; setPayAmount: (value: string) => void; method: PaymentMethod; setMethod: (value: PaymentMethod) => void; note: string; setNote: (value: string) => void; chargeId: string; setChargeId: (value: string) => void; submit: (event: FormEvent) => Promise<void>; pending: boolean }) { return <div><PageHeader eyebrow="Mis cuentas" title="Todo claro, sin sorpresas." description="Consulta tus cargos y registra un pago. El saldo solo cambia cuando la administración lo confirma." /><section className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-3xl bg-sidebar p-7 text-sidebar-foreground"><p className="eyebrow text-sky-200">Saldo pendiente</p><p className="mt-4 text-5xl font-semibold">{euro((statement?.charges ?? []).filter(item => item.status !== "cancelled").reduce((sum, item) => sum + item.amountCents, 0) - (statement?.payments ?? []).filter(item => item.status === "confirmed").reduce((sum, item) => sum + item.amountCents, 0))}</p></article><form onSubmit={submit} className="paper-card p-7"><p className="eyebrow">Nuevo pago</p><h2 className="display-face mt-1 text-3xl">Solicitar confirmación</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><SelectField label="Cargo relacionado" value={chargeId} onChange={setChargeId} options={(statement?.charges ?? []).filter(item => item.status === "open").map(item => ({ value: String(item.id), label: `${item.concept} · ${euro(item.amountCents)}` }))} /><FormField label="Importe (€)" value={payAmount} onChange={setPayAmount} type="number" step="0.01" required /><SelectField label="Método" value={method} onChange={value => setMethod(value as PaymentMethod)} options={[{ value: "cash", label: "Efectivo" }, { value: "bank_transfer", label: "Transferencia" }, { value: "bizum", label: "Bizum" }, { value: "paypal", label: "PayPal" }]} noNone /><div className="sm:col-span-2"><Label>Nota opcional</Label><Textarea value={note} onChange={event => setNote(event.target.value)} className="mt-2 rounded-xl" placeholder="Referencia, aclaración…" /></div></div><Button disabled={pending} className="mt-5 rounded-xl" type="submit">Enviar pago pendiente</Button></form></section><StatementList statement={statement} /></div>; }
function SelectField({ label, value, onChange, options, noNone = false, noneLabel = "Sin asignar" }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }>; noNone?: boolean; noneLabel?: string }) { return <div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Seleccionar" /></SelectTrigger><SelectContent>{!noNone ? <SelectItem value="none">{noneLabel}</SelectItem> : null}{options.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
function FormField({ label, value, onChange, type = "text", step, required, placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; step?: string; required?: boolean; placeholder?: string }) { return <div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</Label><Input value={value} onChange={event => onChange(event.target.value)} type={type} step={step} required={required} placeholder={placeholder} className="rounded-xl" /></div>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</Label><Input value={value} onChange={event => onChange(event.target.value)} type="date" required className="rounded-xl" /></div>; }
function BalanceTile({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <article className="paper-card p-5"><div className="flex items-center justify-between"><p className="eyebrow">{label}</p><span className="text-primary">{icon}</span></div><p className="mt-5 text-3xl font-semibold">{value}</p></article>; }
function ActionChip({ icon, label, onClick }: { icon: React.ReactNode; label: string; onClick: () => void }) { return <Button onClick={onClick} variant="outline" size="sm" className="rounded-xl">{icon}<span className="ml-2">{label}</span></Button>; }
function Empty({ text }: { text: string }) { return <p className="px-6 py-9 text-sm text-muted-foreground">{text}</p>; }
function StatementList({ statement }: { statement: PlayerStatement | undefined }) { return <section className="mt-7 paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Detalle</p><h2 className="display-face mt-1 text-2xl">Mis movimientos</h2></div><div className="divide-y divide-border/70">{statement?.charges.map(charge => <div className="flex items-center justify-between px-6 py-4" key={`charge-${charge.id}`}><div><p className="text-sm font-semibold">{charge.concept}</p><p className="mt-1 text-xs text-muted-foreground">Cargo · {charge.status === "settled" ? "Liquidado" : charge.status === "cancelled" ? "Cancelado" : "Abierto"}</p></div><p className="font-bold text-rose-700">{euro(charge.amountCents)}</p></div>)}{statement?.payments.map(payment => <div className="flex items-center justify-between px-6 py-4" key={`payment-${payment.id}`}><div><p className="text-sm font-semibold">{payment.concept || "Pago"} · {payment.method === "bizum" ? "Bizum" : payment.method === "cash" ? "Efectivo" : payment.method === "paypal" ? "PayPal" : "Transferencia"}</p><p className="mt-1 text-xs text-muted-foreground">{payment.status === "confirmed" ? "Confirmado" : payment.status === "pending" ? "Pendiente de confirmar" : "Rechazado"}</p></div><p className="font-bold text-emerald-700">{euro(payment.amountCents)}</p></div>)}{!statement?.charges.length && !statement?.payments.length ? <Empty text="Aún no tienes movimientos." /> : null}</div></section>; }
