import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { euro, shortDate } from "@/lib/format";
import { Check, CircleDollarSign, Clock3, Plus, ReceiptText } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const toCents = (value: string) => Math.round(Number(value.replace(",", ".")) * 100);
type PlayerStatement = {
  charges: Array<{ id: number; concept: string; status: "open" | "cancelled" | "settled"; amountCents: number }>;
  payments: Array<{ id: number; method: "cash" | "bank_transfer" | "bizum" | "paypal"; status: "pending" | "confirmed" | "rejected"; amountCents: number }>;
};

export default function FinancesPage() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const statement = trpc.finance.myStatement.useQuery(undefined, { enabled: !isAdmin });
  const ledger = trpc.finance.ledger.useQuery(undefined, { enabled: isAdmin });
  const queue = trpc.finance.paymentQueue.useQuery(undefined, { enabled: isAdmin });
  const balances = trpc.finance.playerBalances.useQuery(undefined, { enabled: isAdmin });
  const review = trpc.finance.reviewPayment.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Pago revisado."); } });
  const submit = trpc.finance.submitPayment.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Pago enviado. Queda pendiente de confirmar."); } });
  const transaction = trpc.finance.createTransaction.useMutation({ onSuccess: () => { utils.finance.ledger.invalidate(); toast.success("Movimiento contable registrado."); } });
  const createCharges = trpc.finance.createCharges.useMutation({ onSuccess: () => { utils.finance.invalidate(); toast.success("Cargo individual creado."); } });
  const [payAmount, setPayAmount] = useState(""); const [method, setMethod] = useState<"cash" | "bank_transfer" | "bizum" | "paypal">("bizum"); const [note, setNote] = useState("");
  const [showTransaction, setShowTransaction] = useState(false); const [concept, setConcept] = useState(""); const [transactionAmount, setTransactionAmount] = useState(""); const [direction, setDirection] = useState<"income" | "expense">("expense");
  const [showCharge, setShowCharge] = useState(false); const [chargePlayerId, setChargePlayerId] = useState(""); const [chargeConcept, setChargeConcept] = useState(""); const [chargeAmount, setChargeAmount] = useState("");
  const submitPayment = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(payAmount); if (!Number.isFinite(amountCents) || amountCents <= 0) return toast.error("Indica un importe válido."); await submit.mutateAsync({ amountCents, method, paidAt: new Date(), playerNote: note || null }); setPayAmount(""); setNote(""); };
  const submitTransaction = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(transactionAmount); if (!concept || !Number.isFinite(amountCents) || amountCents <= 0) return toast.error("Completa concepto e importe."); await transaction.mutateAsync({ concept, amountCents, direction, occurredAt: new Date() }); setConcept(""); setTransactionAmount(""); setShowTransaction(false); };
  const submitCharge = async (event: FormEvent) => { event.preventDefault(); const amountCents = toCents(chargeAmount); if (!chargePlayerId || !chargeConcept || !Number.isFinite(amountCents) || amountCents <= 0) return toast.error("Selecciona jugador, concepto e importe."); await createCharges.mutateAsync({ playerIds: [Number(chargePlayerId)], concept: chargeConcept, amountCents }); setChargePlayerId(""); setChargeConcept(""); setChargeAmount(""); setShowCharge(false); };

  if (!isAdmin) return <div><PageHeader eyebrow="Mis cuentas" title="Todo claro, sin sorpresas." description="Consulta tus cargos y registra un pago. El saldo solo se actualiza cuando la administración lo confirma." /><section className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-3xl bg-sidebar p-7 text-sidebar-foreground"><p className="eyebrow text-sky-200">Saldo pendiente</p><p className="mt-4 text-5xl font-semibold">{euro(statement.data?.summary.balanceCents ?? 0)}</p><div className="mt-6 grid grid-cols-2 gap-3 border-t border-white/10 pt-5 text-sm"><div><p className="text-sky-100/65">Cargos</p><p className="mt-1 font-bold">{euro(statement.data?.summary.chargedCents ?? 0)}</p></div><div><p className="text-sky-100/65">Pendiente de confirmar</p><p className="mt-1 font-bold">{euro(statement.data?.summary.pendingCents ?? 0)}</p></div></div></article><form onSubmit={submitPayment} className="paper-card p-7"><p className="eyebrow">Nuevo pago</p><h2 className="display-face mt-1 text-3xl">Solicitar confirmación</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><FormField label="Importe (€)" value={payAmount} onChange={setPayAmount} type="number" step="0.01" required /><div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Método</Label><Select value={method} onValueChange={value => setMethod(value as typeof method)}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">Efectivo</SelectItem><SelectItem value="bank_transfer">Transferencia</SelectItem><SelectItem value="bizum">Bizum</SelectItem><SelectItem value="paypal">PayPal</SelectItem></SelectContent></Select></div><div className="sm:col-span-2 space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Nota opcional</Label><Textarea value={note} onChange={event => setNote(event.target.value)} className="rounded-xl" placeholder="Referencia, aclaración…" /></div></div><Button disabled={submit.isPending} className="mt-5 rounded-xl" type="submit">Enviar pago pendiente</Button></form></section><StatementList statement={statement.data} /></div>;

  const owed = balances.data?.reduce((sum, item) => sum + Math.max(item.summary.balanceCents, 0), 0) ?? 0;
  return <div><PageHeader eyebrow="Contabilidad" title="La caja, bajo control." description="Movimientos del equipo, saldos individuales y pagos que requieren validación administrativa." action={<div className="flex gap-2"><Button onClick={() => setShowCharge(!showCharge)} variant="outline" className="rounded-xl">Nueva cuota</Button><Button onClick={() => setShowTransaction(!showTransaction)} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Movimiento</Button></div>} />
    {showCharge ? <form onSubmit={submitCharge} className="paper-card mb-6 grid gap-4 p-5 md:grid-cols-4"><div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Jugador</Label><Select value={chargePlayerId} onValueChange={setChargePlayerId}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Elegir" /></SelectTrigger><SelectContent>{balances.data?.filter(item => item.player.status === "active").map(item => <SelectItem key={item.player.id} value={String(item.player.id)}>{item.player.fullName}</SelectItem>)}</SelectContent></Select></div><FormField label="Concepto" value={chargeConcept} onChange={setChargeConcept} required /><FormField label="Importe (€)" value={chargeAmount} onChange={setChargeAmount} type="number" step="0.01" required /><div className="flex items-end"><Button type="submit" className="w-full rounded-xl">Crear cargo</Button></div></form> : null}
    {showTransaction ? <form onSubmit={submitTransaction} className="paper-card mb-6 grid gap-4 p-5 md:grid-cols-4"><FormField label="Concepto" value={concept} onChange={setConcept} required /><FormField label="Importe (€)" value={transactionAmount} onChange={setTransactionAmount} type="number" step="0.01" required /><div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Tipo</Label><Select value={direction} onValueChange={value => setDirection(value as typeof direction)}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="expense">Gasto</SelectItem><SelectItem value="income">Ingreso</SelectItem></SelectContent></Select></div><div className="flex items-end"><Button type="submit" className="w-full rounded-xl">Guardar</Button></div></form> : null}
    <section className="grid gap-4 md:grid-cols-3"><BalanceTile label="Saldo del equipo" value={euro(ledger.data?.generalBalanceCents ?? 0)} icon={<CircleDollarSign className="h-5 w-5" />} /><BalanceTile label="Por cobrar" value={euro(owed)} icon={<ReceiptText className="h-5 w-5" />} /><BalanceTile label="Pagos pendientes" value={String(queue.data?.length ?? 0)} icon={<Clock3 className="h-5 w-5" />} /></section>
    <section className="mt-7 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Confirmaciones</p><h2 className="display-face mt-1 text-2xl">Pendientes de validar</h2></div><div className="divide-y divide-border/70">{queue.data?.length ? queue.data.map(item => <div key={item.payment.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p className="font-semibold">{item.playerName}</p><p className="mt-1 text-xs text-muted-foreground">{shortDate(item.payment.paidAt)} · {item.payment.method === "bizum" ? "Bizum" : item.payment.method === "cash" ? "Efectivo" : item.payment.method === "paypal" ? "PayPal" : "Transferencia"}</p></div><div className="flex items-center gap-3"><p className="font-bold">{euro(item.payment.amountCents)}</p><Button onClick={() => review.mutate({ id: item.payment.id, decision: "confirmed" })} size="sm" className="rounded-lg"><Check className="mr-1 h-3.5 w-3.5" />Confirmar</Button><Button onClick={() => review.mutate({ id: item.payment.id, decision: "rejected" })} size="sm" variant="ghost" className="rounded-lg text-muted-foreground">Rechazar</Button></div></div>) : <p className="px-6 py-9 text-sm text-muted-foreground">No hay pagos pendientes.</p>}</div></article><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Saldos individuales</p><h2 className="display-face mt-1 text-2xl">Quién debe</h2></div><div className="divide-y divide-border/70">{balances.data?.filter(item => item.summary.balanceCents !== 0).slice(0, 8).map(item => <div className="flex items-center justify-between px-6 py-4" key={item.player.id}><div><p className="text-sm font-semibold">{item.player.fullName}</p><p className="mt-1 text-xs text-muted-foreground">{item.player.status === "active" ? "Activo" : "Baja archivada"}</p></div><p className={item.summary.balanceCents > 0 ? "font-bold text-rose-700" : "font-bold text-emerald-700"}>{euro(item.summary.balanceCents)}</p></div>) || <p className="px-6 py-9 text-sm text-muted-foreground">Sin saldos pendientes.</p>}</div></article></section>
  </div>;
}

function FormField({ label, value, onChange, type = "text", step, required }: { label: string; value: string; onChange: (value: string) => void; type?: string; step?: string; required?: boolean }) { return <div className="space-y-2"><Label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</Label><Input value={value} onChange={event => onChange(event.target.value)} type={type} step={step} required={required} className="rounded-xl" /></div>; }
function BalanceTile({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <article className="paper-card p-5"><div className="flex items-center justify-between"><p className="eyebrow">{label}</p><span className="text-primary">{icon}</span></div><p className="mt-5 text-3xl font-semibold">{value}</p></article>; }
function StatementList({ statement }: { statement: PlayerStatement | undefined }) { return <section className="mt-7 paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Detalle</p><h2 className="display-face mt-1 text-2xl">Mis movimientos</h2></div><div className="divide-y divide-border/70">{statement?.charges.map(charge => <div className="flex items-center justify-between px-6 py-4" key={`charge-${charge.id}`}><div><p className="text-sm font-semibold">{charge.concept}</p><p className="mt-1 text-xs text-muted-foreground">Cargo · {charge.status === "settled" ? "Liquidado" : charge.status === "cancelled" ? "Cancelado" : "Abierto"}</p></div><p className="font-bold text-rose-700">{euro(charge.amountCents)}</p></div>)}{statement?.payments.map(payment => <div className="flex items-center justify-between px-6 py-4" key={`payment-${payment.id}`}><div><p className="text-sm font-semibold">Pago · {payment.method === "bizum" ? "Bizum" : payment.method === "cash" ? "Efectivo" : payment.method === "paypal" ? "PayPal" : "Transferencia"}</p><p className="mt-1 text-xs text-muted-foreground">{payment.status === "confirmed" ? "Confirmado" : payment.status === "pending" ? "Pendiente de confirmar" : "Rechazado"}</p></div><p className="font-bold text-emerald-700">{euro(payment.amountCents)}</p></div>)}{!statement?.charges.length && !statement?.payments.length ? <p className="px-6 py-9 text-sm text-muted-foreground">Aún no tienes movimientos.</p> : null}</div></section>; }
