import { AdminOnly } from "@/components/AdminOnly";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { shortDate } from "@/lib/format";
import { FileSearch, FileUp, LoaderCircle, Sparkles } from "lucide-react";
import { ChangeEvent, useState } from "react";
import { toast } from "sonner";

type ExtractedItem = { recordType: string; summary: string; rawFields: string; confidence: number };
type ExtractionResult = { documentSummary: string; items: ExtractedItem[]; warnings: string[] };

export default function ImportPage() { return <AdminOnly><ImportWorkspace /></AdminOnly>; }

function ImportWorkspace() {
  const utils = trpc.useUtils(); const jobs = trpc.imports.list.useQuery(); const upload = trpc.imports.uploadAndExtract.useMutation({ onSuccess: () => utils.imports.list.invalidate() }); const review = trpc.imports.review.useMutation({ onSuccess: () => utils.imports.list.invalidate() });
  const [type, setType] = useState<"calendar" | "standing" | "match_report" | "financial" | "other">("calendar"); const [result, setResult] = useState<ExtractionResult | null>(null); const [filename, setFilename] = useState("");
  const uploadFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    const isPdf = file.type === "application/pdf"; const isImage = file.type.startsWith("image/"); if (!isPdf && !isImage) return toast.error("Selecciona una imagen o un PDF."); if (file.size > 15 * 1024 * 1024) return toast.error("El documento supera el límite de 15 MB.");
    setFilename(file.name); const base64 = await readBase64(file);
    try { const response = await upload.mutateAsync({ type, sourceKind: isPdf ? "pdf" : "image", originalFilename: file.name, mimeType: file.type, base64 }); setResult(response.result as ExtractionResult); toast.success("Borrador extraído. Revísalo antes de registrar datos."); } catch { toast.error("No se ha podido extraer el documento."); }
    event.target.value = "";
  };
  return <div><PageHeader eyebrow="Importación asistida" title="Del documento al borrador." description="Sube una imagen o PDF de un acta, clasificación, calendario o cuenta. La extracción es un borrador que requiere revisión antes de crear registros." />
    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><article className="paper-card p-7"><p className="eyebrow">Nuevo documento</p><h2 className="display-face mt-1 text-3xl">Preparar importación</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">La plataforma no modifica ningún dato automáticamente. Solo propone campos legibles para que puedas contrastarlos.</p><div className="mt-6 space-y-2"><label className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Destino del borrador</label><Select value={type} onValueChange={value => setType(value as typeof type)}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="calendar">Calendario</SelectItem><SelectItem value="standing">Clasificación</SelectItem><SelectItem value="match_report">Acta o resultado</SelectItem><SelectItem value="financial">Contabilidad</SelectItem><SelectItem value="other">Otro</SelectItem></SelectContent></Select></div><label className="mt-5 flex min-h-40 flex-col items-center justify-center rounded-2xl border border-dashed border-primary/35 bg-accent/30 px-5 text-center transition hover:bg-accent/60"><input type="file" accept="image/*,application/pdf" className="sr-only" onChange={uploadFile} /><span className="grid h-11 w-11 place-items-center rounded-2xl bg-primary text-primary-foreground">{upload.isPending ? <LoaderCircle className="h-5 w-5 animate-spin" /> : <FileUp className="h-5 w-5" />}</span><span className="mt-3 text-sm font-bold">{upload.isPending ? "Extrayendo información…" : "Seleccionar imagen o PDF"}</span><span className="mt-1 text-xs text-muted-foreground">Máximo 15 MB · {filename || "sin archivo"}</span></label></article>
      <article className="paper-card overflow-hidden"><div className="flex items-center gap-3 border-b border-border/70 px-6 py-5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-100 text-amber-700"><Sparkles className="h-4 w-4" /></span><div><p className="eyebrow">Resultado asistido</p><h2 className="display-face mt-1 text-2xl">Borrador de revisión</h2></div></div>{result ? <div className="p-6"><p className="text-sm leading-6 text-muted-foreground">{result.documentSummary}</p><div className="mt-5 space-y-3">{result.items.map((item, index) => <div key={`${item.recordType}-${index}`} className="rounded-xl bg-secondary/65 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wider text-primary">{item.recordType}</p><Badge variant="secondary">{item.confidence}% confianza</Badge></div><p className="mt-2 font-semibold">{item.summary}</p><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{item.rawFields}</p></div>)}</div>{result.warnings.length ? <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Revisar antes de guardar:</strong><br />{result.warnings.join(" · ")}</div> : null}</div> : <div className="p-10 text-center"><FileSearch className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm text-muted-foreground">Aquí aparecerá el borrador del documento seleccionado.</p></div>}</article></section>
    <section className="mt-7 paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Historial</p><h2 className="display-face mt-1 text-2xl">Importaciones guardadas</h2></div><div className="divide-y divide-border/70">{jobs.data?.length ? jobs.data.map(job => <div key={job.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p className="font-semibold">{job.originalFilename}</p><p className="mt-1 text-xs text-muted-foreground">{job.type} · {shortDate(job.createdAt)}</p></div><div className="flex items-center gap-2"><Badge variant="secondary">{job.status === "ready_for_review" ? "Listo para revisar" : job.status === "approved" ? "Revisado" : job.status === "discarded" ? "Descartado" : job.status === "failed" ? "Con error" : job.status}</Badge>{job.status === "ready_for_review" ? <><Button onClick={() => review.mutate({ id: job.id, decision: "approved" })} size="sm" className="rounded-lg">Revisado</Button><Button onClick={() => review.mutate({ id: job.id, decision: "discarded" })} size="sm" variant="ghost" className="rounded-lg">Descartar</Button></> : null}</div></div>) : <p className="p-7 text-sm text-muted-foreground">Aún no hay importaciones.</p>}</div></section>
  </div>;
}
function readBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(reader.error); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }
