import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { dateTime } from "@/lib/format";
import { Medal, Plus, Trophy } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { ImdSyncPanel } from "@/components/ImdSyncPanel";

export default function SportsPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const seasons = trpc.sports.seasons.useQuery(); const competitions = trpc.sports.competitions.useQuery(); const games = trpc.sports.matches.useQuery();
  const [selectedCompetition, setSelectedCompetition] = useState<number | null>(null); useEffect(() => { if (!selectedCompetition && competitions.data?.[0]) setSelectedCompetition(competitions.data[0].id); }, [competitions.data, selectedCompetition]);
  const standings = trpc.sports.standings.useQuery({ competitionId: selectedCompetition ?? 1 }, { enabled: Boolean(selectedCompetition) });
  const createSeason = trpc.sports.createSeason.useMutation({ onSuccess: () => { utils.sports.seasons.invalidate(); toast.success("Temporada creada."); } });
  const createCompetition = trpc.sports.createCompetition.useMutation({ onSuccess: () => { utils.sports.competitions.invalidate(); toast.success("Competición creada."); } });
  const createMatch = trpc.sports.createMatch.useMutation({ onSuccess: () => { utils.sports.matches.invalidate(); utils.sports.events.invalidate(); utils.sports.nextSummary.invalidate(); toast.success("Partido registrado."); } });
  const [showSeason, setShowSeason] = useState(false); const [showCompetition, setShowCompetition] = useState(false); const [showMatch, setShowMatch] = useState(false); const [seasonName, setSeasonName] = useState(""); const [seasonStart, setSeasonStart] = useState(""); const [seasonEnd, setSeasonEnd] = useState(""); const [competitionName, setCompetitionName] = useState(""); const [competitionSeason, setCompetitionSeason] = useState(""); const [phase, setPhase] = useState("Fase regular"); const [opponent, setOpponent] = useState(""); const [matchDate, setMatchDate] = useState(""); const [callAt, setCallAt] = useState(""); const [matchLocation, setMatchLocation] = useState(""); const [matchVenue, setMatchVenue] = useState<"home" | "away" | "neutral">("home"); const [matchCompetition, setMatchCompetition] = useState(""); const [ownScore, setOwnScore] = useState(""); const [opponentScore, setOpponentScore] = useState("");
  const saveSeason = async (event: FormEvent) => { event.preventDefault(); if (!seasonStart || !seasonEnd) return toast.error("Completa las fechas de la temporada."); await createSeason.mutateAsync({ name: seasonName, startsAt: new Date(seasonStart), endsAt: new Date(seasonEnd) }); setShowSeason(false); setSeasonName(""); };
  const saveCompetition = async (event: FormEvent) => { event.preventDefault(); if (!competitionSeason) return toast.error("Selecciona una temporada."); await createCompetition.mutateAsync({ seasonId: Number(competitionSeason), name: competitionName, phase }); setShowCompetition(false); setCompetitionName(""); };
  const saveMatch = async (event: FormEvent) => { event.preventDefault(); if (!opponent || !matchDate) return toast.error("Completa rival y fecha."); const finished = ownScore !== "" && opponentScore !== ""; await createMatch.mutateAsync({ type: "match", title: `Buyuyus vs ${opponent}`, opponent, startsAt: new Date(matchDate), callAt: callAt ? new Date(callAt) : null, location: matchLocation || null, venue: matchVenue, competitionId: matchCompetition ? Number(matchCompetition) : null, ownScore: finished ? Number(ownScore) : null, opponentScore: finished ? Number(opponentScore) : null, status: finished ? "completed" : "scheduled" }); setShowMatch(false); setOpponent(""); setMatchDate(""); setCallAt(""); setMatchLocation(""); setOwnScore(""); setOpponentScore(""); };
  return <div><PageHeader eyebrow="Temporadas y resultados" title="Cada partido deja historia." description="Conserva fases regulares, playoffs, copas y clasificaciones para consultar cualquier temporada del equipo." action={isAdmin ? <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setShowSeason(!showSeason)} className="rounded-xl">Temporada</Button><Button variant="outline" onClick={() => setShowCompetition(!showCompetition)} className="rounded-xl">Competición</Button><Button onClick={() => setShowMatch(!showMatch)} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Partido</Button></div> : undefined} />
    {showSeason ? <form onSubmit={saveSeason} className="paper-card mb-5 grid gap-4 p-5 md:grid-cols-4"><SportField label="Nombre" value={seasonName} onChange={setSeasonName} placeholder="2026–2027" required /><SportField label="Inicio" value={seasonStart} onChange={setSeasonStart} type="date" required /><SportField label="Fin" value={seasonEnd} onChange={setSeasonEnd} type="date" required /><div className="flex items-end"><Button type="submit" className="w-full rounded-xl">Guardar temporada</Button></div></form> : null}
    {showCompetition ? <form onSubmit={saveCompetition} className="paper-card mb-5 grid gap-4 p-5 md:grid-cols-4"><SportField label="Nombre" value={competitionName} onChange={setCompetitionName} placeholder="Juegos Municipales" required /><SportField label="Fase" value={phase} onChange={setPhase} placeholder="Fase regular" required /><div className="space-y-2"><Label>Temporada</Label><Select value={competitionSeason} onValueChange={setCompetitionSeason}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Elegir" /></SelectTrigger><SelectContent>{seasons.data?.map(season => <SelectItem key={season.id} value={String(season.id)}>{season.name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button type="submit" className="w-full rounded-xl">Guardar competición</Button></div></form> : null}
    {showMatch ? <form onSubmit={saveMatch} className="paper-card mb-5 grid gap-4 p-5 md:grid-cols-4 xl:grid-cols-7"><SportField label="Rival" value={opponent} onChange={setOpponent} required /><SportField label="Fecha y hora" value={matchDate} onChange={setMatchDate} type="datetime-local" required /><SportField label="Hora de estar" value={callAt} onChange={setCallAt} type="datetime-local" /><SportField label="Lugar" value={matchLocation} onChange={setMatchLocation} placeholder="Pabellón o pista" /><div className="space-y-2"><Label>Condición</Label><Select value={matchVenue} onValueChange={value => setMatchVenue(value as "home" | "away" | "neutral")}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="home">Local</SelectItem><SelectItem value="away">Visitante</SelectItem><SelectItem value="neutral">Neutral</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Competición</Label><Select value={matchCompetition || "none"} onValueChange={value => setMatchCompetition(value === "none" ? "" : value)}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Sin asignar" /></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{competitions.data?.map(competition => <SelectItem key={competition.id} value={String(competition.id)}>{competition.name}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-2"><SportField label="P. Buyuyus" value={ownScore} onChange={setOwnScore} type="number" /><SportField label="P. rival" value={opponentScore} onChange={setOpponentScore} type="number" /></div><div className="md:col-span-4 xl:col-span-7 flex justify-end"><Button type="submit" className="rounded-xl">Guardar partido</Button></div></form> : null}
    <section className="grid gap-5 xl:grid-cols-[.9fr_1.1fr]"><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Archivo</p><h2 className="display-face mt-1 text-2xl">Temporadas</h2></div><div className="divide-y divide-border/70">{seasons.data?.length ? seasons.data.map(season => <div className="flex items-center justify-between px-6 py-4" key={season.id}><div><p className="font-semibold">{season.name}</p><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat("es-ES", { month: "short", year: "numeric" }).format(new Date(season.startsAt))} — {new Intl.DateTimeFormat("es-ES", { month: "short", year: "numeric" }).format(new Date(season.endsAt))}</p></div>{season.isCurrent ? <Badge className="bg-emerald-100 text-emerald-800 hover:bg-emerald-100">Actual</Badge> : <Badge variant="secondary">Histórica</Badge>}</div>) : <p className="p-7 text-sm text-muted-foreground">Crea la primera temporada.</p>}</div></article><article className="paper-card overflow-hidden"><div className="border-b border-border/70 px-6 py-5"><p className="eyebrow">Competiciones</p><h2 className="display-face mt-1 text-2xl">Clasificación</h2><p className="mt-1 text-xs text-muted-foreground">Se recalcula automáticamente al confirmar cada resultado.</p></div><div className="p-5"><Select value={selectedCompetition?.toString() ?? ""} onValueChange={value => setSelectedCompetition(Number(value))}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Seleccionar competición" /></SelectTrigger><SelectContent>{competitions.data?.map(competition => <SelectItem key={competition.id} value={String(competition.id)}>{competition.name}{competition.phase ? ` · ${competition.phase}` : ""}</SelectItem>)}</SelectContent></Select></div><div className="border-t border-border/70">{standings.data?.length ? standings.data.map(row => <div key={row.id} className="grid grid-cols-[2rem_1fr_2rem_2.5rem] items-center gap-2 px-6 py-3 text-sm"><span className="font-bold text-muted-foreground">{row.position ?? "—"}</span><span className="font-semibold">{row.teamName}</span><span>{row.played}</span><span className="text-right font-bold">{row.points}</span></div>) : <div className="p-7 text-sm text-muted-foreground">Todavía no hay clasificación para esta competición.</div>}</div></article></section>
    {isAdmin ? <ImdSyncPanel /> : null}
    <section className="mt-7 paper-card overflow-hidden"><div className="flex items-center justify-between border-b border-border/70 px-6 py-5"><div><p className="eyebrow">Archivo completo</p><h2 className="display-face mt-1 text-2xl">Historial de resultados</h2></div><Trophy className="h-5 w-5 text-amber-600" /></div><div className="divide-y divide-border/70">{games.data?.length ? games.data.map(item => <div key={item.match.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><div><p className="font-semibold">Buyuyus <span className="font-normal text-muted-foreground">vs</span> {item.match.opponent}</p><p className="mt-1 text-xs text-muted-foreground">{dateTime(item.event.startsAt)} · {item.competitionName ?? "Sin competición"} · {item.seasonName ?? "Sin temporada"}</p></div><div className="flex items-center gap-3"><Badge variant="secondary">{item.match.venue === "home" ? "Local" : item.match.venue === "away" ? "Visitante" : "Neutral"}</Badge><p className="text-lg font-bold">{item.match.ownScore === null ? "—" : `${item.match.ownScore}–${item.match.opponentScore}`}</p></div></div>) : <div className="p-8 text-center text-sm text-muted-foreground"><Medal className="mx-auto mb-3 h-6 w-6" />No hay partidos registrados.</div>}</div></section>
  </div>;
}
function SportField({ label, value, onChange, type = "text", placeholder, required }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string; required?: boolean }) { return <div className="space-y-2"><Label>{label}</Label><Input className="rounded-xl" value={value} onChange={event => onChange(event.target.value)} type={type} placeholder={placeholder} required={required} /></div>; }
