import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { dateTime } from "@/lib/format";
import { Check, Clock3, MapPin, Plus, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

export default function TrainingPage() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const events = trpc.sports.events.useQuery({ limit: 200 }); const seasons = trpc.sports.seasons.useQuery();
  const create = trpc.sports.createEvent.useMutation({ onSuccess: () => { utils.sports.events.invalidate(); utils.sports.nextSummary.invalidate(); toast.success("Entrenamiento programado."); } });
  const respond = trpc.sports.respondAttendance.useMutation({ onSuccess: () => { utils.sports.events.invalidate(); utils.sports.nextSummary.invalidate(); toast.success("Asistencia actualizada."); } });
  const [showForm, setShowForm] = useState(false); const [startsAt, setStartsAt] = useState(""); const [callAt, setCallAt] = useState(""); const [location, setLocation] = useState(""); const [seasonId, setSeasonId] = useState("");
  const trainings = useMemo(() => (events.data ?? []).filter(item => item.event.type === "training"), [events.data]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!startsAt) return toast.error("Indica fecha y hora."); await create.mutateAsync({ type: "training", title: "Entrenamiento", startsAt: new Date(startsAt), callAt: callAt ? new Date(callAt) : null, location: location || null, seasonId: seasonId ? Number(seasonId) : null, attendanceEnabled: true }); setShowForm(false); setStartsAt(""); setCallAt(""); setLocation(""); };
  return <div><PageHeader eyebrow="Entrenamientos" title="La pista empieza antes de entrenar." description="Programa cada sesión, comunica la hora de estar y consulta quién confirma asistencia." action={isAdmin ? <Button onClick={() => setShowForm(!showForm)} className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Programar entrenamiento</Button> : undefined} />
    {showForm ? <form onSubmit={submit} className="paper-card mb-6 grid gap-4 p-5 md:grid-cols-5"><TrainingField label="Fecha y hora" value={startsAt} onChange={setStartsAt} type="datetime-local" required /><TrainingField label="Hora de estar" value={callAt} onChange={setCallAt} type="datetime-local" /><TrainingField label="Lugar" value={location} onChange={setLocation} placeholder="Pabellón o pista" /><div className="space-y-2"><Label>Temporada</Label><Select value={seasonId || "none"} onValueChange={value => setSeasonId(value === "none" ? "" : value)}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Sin asignar" /></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{seasons.data?.map(season => <SelectItem key={season.id} value={String(season.id)}>{season.name}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end gap-2"><Button type="button" variant="ghost" onClick={() => setShowForm(false)}>Cancelar</Button><Button type="submit" disabled={create.isPending} className="flex-1 rounded-xl">Guardar</Button></div></form> : null}
    <section className="space-y-3">{trainings.length ? trainings.map(item => <article key={item.event.id} className="paper-card p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex items-center gap-2"><h2 className="display-face text-2xl">{item.event.title}</h2><Badge className="bg-sky-100 text-sky-800 hover:bg-sky-100">Entrenamiento</Badge></div><p className="mt-2 text-sm text-muted-foreground">{dateTime(item.event.startsAt)}{item.event.location ? ` · ${item.event.location}` : ""}</p>{item.event.callAt ? <p className="mt-3 flex items-center gap-2 rounded-lg bg-sky-50 px-3 py-2 text-sm font-semibold text-sky-800"><Clock3 className="h-4 w-4" />Hora de estar: {dateTime(item.event.callAt)}</p> : null}{item.event.location ? <p className="mt-3 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="h-4 w-4" />{item.event.location}</p> : null}</div><div className="rounded-xl bg-secondary/60 px-4 py-3 text-sm"><p className="font-semibold">Asistencia</p><p className="mt-1 text-muted-foreground">{item.attendance.going} sí · {item.attendance.maybe} quizá · {item.attendance.notGoing} no</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Attendance active={item.attendance.mine === "going"} icon={<Check className="h-3.5 w-3.5" />} label="Voy" onClick={() => respond.mutate({ eventId: item.event.id, status: "going" })} /><Attendance active={item.attendance.mine === "maybe"} icon={<Clock3 className="h-3.5 w-3.5" />} label="Quizá" onClick={() => respond.mutate({ eventId: item.event.id, status: "maybe" })} /><Attendance active={item.attendance.mine === "not_going"} icon={<X className="h-3.5 w-3.5" />} label="No voy" onClick={() => respond.mutate({ eventId: item.event.id, status: "not_going" })} /></div></article>) : <article className="paper-card p-10 text-center text-sm text-muted-foreground">No hay entrenamientos programados. Los que programes aquí aparecerán también en Calendario y en el resumen.</article>}</section>
  </div>;
}
function Attendance({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <Button onClick={onClick} variant={active ? "default" : "outline"} size="sm" className="rounded-lg">{icon}<span className="ml-1.5">{label}</span></Button>; }
function TrainingField({ label, value, onChange, type = "text", required, placeholder }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; placeholder?: string }) { return <div className="space-y-2"><Label>{label}</Label><Input value={value} onChange={event => onChange(event.target.value)} type={type} placeholder={placeholder} required={required} className="rounded-xl" /></div>; }
